Moved output_files page to same level as input_files (was a subdir).
castep-docs/castep-docs pull request #98
Opened 2024-06-03 13:56 UTC by krefson

Enhanced content of output_files to describe most known CASTEP output files.

2024-06-08 21:07 UTC, oerc0122 requested changes
This needs updating in the `mkdocs.yml` too, to point to new folder.

2024-06-08 21:07 UTC, oerc0122 commented on docs/documentation/Output_Files/output_files.md
>  ASCII. X-ray structure factors. See the [documentation page](documentation/XRD/overview)
```suggestion
ASCII. X-ray structure factors. See the [documentation page](/documentation/XRD/overview)
```

2024-06-08 21:07 UTC, oerc0122 commented on docs/documentation/Output_Files/output_files.md
> +ASCII.   Result of ELF calculation.Only written if `write_formatted_elf : T `.
```suggestion
ASCII. Result of ELF calculation. Only written if `write_formatted_elf : T `.
```

2024-06-08 21:07 UTC, oerc0122 commented on docs/documentation/Output_Files/output_files.md
>  ASCII. State of the system (coordinates, unit cell etc) at each step of the molecular dynamics simulation. Same format as the `.geom` file.  See for specification. Can be used to animate the geometry
Incomplete sentence.

2024-06-10 10:27 UTC, krefson commented on docs/documentation/Output_Files/output_files.md
> +ASCII.   Result of ELF calculation.Only written if `write_formatted_elf : T `.
Fixed

2024-06-10 10:29 UTC, krefson commented on docs/documentation/Output_Files/output_files.md
>  ASCII. State of the system (coordinates, unit cell etc) at each step of the molecular dynamics simulation. Same format as the `.geom` file.  See for specification. Can be used to animate the geometry
Fixed

2024-06-10 10:30 UTC, krefson commented on docs/documentation/Output_Files/output_files.md
>  ASCII. X-ray structure factors. See the [documentation page](documentation/XRD/overview)
Fixed

2024-06-10 13:45 UTC, jryates approved these changes

2024-06-10 13:51 UTC, merged